#We use .yml extension to describe workflow to CI CD
name: Pull Request

# below code will execute workflow when pull request is raised to mentioned branch
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
# jobs consist tests
jobs:
  test:
    runs-on: macos-11
    #below are the steps which will run
    steps:
      - uses: actions/checkout@v2
      # Cancel Previous Running test to save time and money
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

          # ruby to install -> gem to install -> bundle
      - uses: ruby/setup-ruby@v1

      - name: Install Bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install

        # checking if cache is present to avoid loading packages again

      - name: Swift Packages Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            Build/SourcePackages
            Build/Build/Products
          key: ${{ runner.os }}-deps-v1-${{ hashFiles('BILDsolid.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
          restore-keys: ${{ runner.os }}-deps-v1-

      - name: Run Tests (No Cache)
        if: steps.setup.outputs.cache-hit != 'true'
        run: bundle exec fastlane unit_test

      - name: Run Tests (Cache)
        if: steps.setup.outputs.cache-hit == 'true'
        run: bundle exec fastlane unit_test skip_package_dependencies_resolution:true
